### ISSUE TITLE
Can't install telepat-api on MacOS with Node 5.1.0

### ISSUE THREAD

**Issue by z4ce** [telepat-io/telepat-cli#2]
It looks like there is a dependency down the stack on node-syslog and node-syslog isn't being maintained for compatibility with the newest versions of node. How are you installing the CLI with newer versions of node?
```
$ npm install telepat-cli
....
 node-syslog@1.2.0 install /Users/user/git/telepat-docker-compose-files/shared/node_modules/node-syslog
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:1:
In file included from ../node-syslog.h:13:
../compat.h:27:2: error: "Unsupported node.js version."
#error "Unsupported node.js version."
````

**Comment by andreimarinescu** [comment]
We haven't worked with 5.1.0 yet as there were some other dependencies that caused issues as well. We'll have a fresh look at this a.s.a.p and replace the syslog dependency with something that is maintained if this is the only dep causing issues.
